//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQC.ConTest {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CQC.ConTest.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command {0}, Transction {1} received with Error Info: {2} 的本地化字符串。
        /// </summary>
        internal static string CmdRcvErr {
            get {
                return ResourceManager.GetString("CmdRcvErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command {0}, Transction {1} received ok. 的本地化字符串。
        /// </summary>
        internal static string CmdRcvOk {
            get {
                return ResourceManager.GetString("CmdRcvOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command {0}, Transction {1} sent ok. 的本地化字符串。
        /// </summary>
        internal static string CmdSentOk {
            get {
                return ResourceManager.GetString("CmdSentOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command communication timeout. 的本地化字符串。
        /// </summary>
        internal static string ErrorTimeout {
            get {
                return ResourceManager.GetString("ErrorTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host 的本地化字符串。
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help for {0} 的本地化字符串。
        /// </summary>
        internal static string IDS_HELP_CAPTION {
            get {
                return ResourceManager.GetString("IDS_HELP_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method Aborting... 的本地化字符串。
        /// </summary>
        internal static string IDS_METH_ABORTING {
            get {
                return ResourceManager.GetString("IDS_METH_ABORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method Aborting... Press OK to continue. 的本地化字符串。
        /// </summary>
        internal static string IDS_METH_ABORTING_OK {
            get {
                return ResourceManager.GetString("IDS_METH_ABORTING_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method execution in progress... 的本地化字符串。
        /// </summary>
        internal static string IDS_METHOD_IN_PROGRESS {
            get {
                return ResourceManager.GetString("IDS_METHOD_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press OK to continue. 的本地化字符串。
        /// </summary>
        internal static string IDS_METHOD_PRESS_OK {
            get {
                return ResourceManager.GetString("IDS_METHOD_PRESS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press OK button to continue method execution or Abort button to abort method execution. 的本地化字符串。
        /// </summary>
        internal static string IDS_METHOD_STATUS_NEXT {
            get {
                return ResourceManager.GetString("IDS_METHOD_STATUS_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No help available. 的本地化字符串。
        /// </summary>
        internal static string IDS_NO_HELP {
            get {
                return ResourceManager.GetString("IDS_NO_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some variable values have changed during the execution of this method .\nCommit or Cancel these changes after leaving the method execution dialog. 的本地化字符串。
        /// </summary>
        internal static string IDS_VAR_VALS_CHANGED {
            get {
                return ResourceManager.GetString("IDS_VAR_VALS_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable {0} can not be written by Commond, please check method. 的本地化字符串。
        /// </summary>
        internal static string NoCmdForVarWrite {
            get {
                return ResourceManager.GetString("NoCmdForVarWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Hart Device Found 的本地化字符串。
        /// </summary>
        internal static string NoDevice {
            get {
                return ResourceManager.GetString("NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string NonePort {
            get {
                return ResourceManager.GetString("NonePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Response 的本地化字符串。
        /// </summary>
        internal static string NoResponse {
            get {
                return ResourceManager.GetString("NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Root Menu 的本地化字符串。
        /// </summary>
        internal static string NoRoot {
            get {
                return ResourceManager.GetString("NoRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No response 的本地化字符串。
        /// </summary>
        internal static string NoRsp {
            get {
                return ResourceManager.GetString("NoRsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Okay 的本地化字符串。
        /// </summary>
        internal static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Port {0} closed. 的本地化字符串。
        /// </summary>
        internal static string portclosed {
            get {
                return ResourceManager.GetString("portclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Port {0} opened. 的本地化字符串。
        /// </summary>
        internal static string portopened {
            get {
                return ResourceManager.GetString("portopened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receiving data 的本地化字符串。
        /// </summary>
        internal static string Receiving {
            get {
                return ResourceManager.GetString("Receiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select DD directory 的本地化字符串。
        /// </summary>
        internal static string SelectDDPath {
            get {
                return ResourceManager.GetString("SelectDDPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending request 的本地化字符串。
        /// </summary>
        internal static string SendingREQ {
            get {
                return ResourceManager.GetString("SendingREQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
