//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfibusDP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProfibusDP.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTO.
        /// </summary>
        internal static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port has been opened.
        /// </summary>
        internal static string BeOpend {
            get {
                return ResourceManager.GetString("BeOpend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFG error.
        /// </summary>
        internal static string CFGErr {
            get {
                return ResourceManager.GetString("CFGErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CFG file.
        /// </summary>
        internal static string CFGNO {
            get {
                return ResourceManager.GetString("CFGNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port has already been closed..
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the port first.
        /// </summary>
        internal static string ClosePort {
            get {
                return ResourceManager.GetString("ClosePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright@zdh.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:\r\n 1. DPMasterSIM DEMO supports single Slave.\r\n2. Max Input/Output Length: 200bytes, Max CFG length: 64bytes, Max PRM Length: 64bytes, \r\n3. Use a RS232/RS485 adpaptor to connect a DP device.\r\n4. DPMasterSIM cannot be used with another DP Master.\r\n\r\n\r\nMannual:\r\n1. To start the DP Master, choose the Port and baudrate first, then Open Port and then start the Master.\r\n2. After the Master is started, all online slave devices will be displayed on the live list, and different color represent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnose overflow.
        /// </summary>
        internal static string DiagOver {
            get {
                return ResourceManager.GetString("DiagOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended diagnose data.
        /// </summary>
        internal static string ExtDiag {
            get {
                return ResourceManager.GetString("ExtDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze mode.
        /// </summary>
        internal static string Freeze {
            get {
                return ResourceManager.GetString("Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web:.
        /// </summary>
        internal static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Address.
        /// </summary>
        internal static string MasterAddr {
            get {
                return ResourceManager.GetString("MasterAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Master.
        /// </summary>
        internal static string MStart {
            get {
                return ResourceManager.GetString("MStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Master.
        /// </summary>
        internal static string MStop {
            get {
                return ResourceManager.GetString("MStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No config!.
        /// </summary>
        internal static string NoCFG {
            get {
                return ResourceManager.GetString("NoCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the CFG first.
        /// </summary>
        internal static string NoCFGFile {
            get {
                return ResourceManager.GetString("NoCFGFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DP master..
        /// </summary>
        internal static string NoMaster {
            get {
                return ResourceManager.GetString("NoMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No port.
        /// </summary>
        internal static string NonePort {
            get {
                return ResourceManager.GetString("NonePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No serial port Selected.
        /// </summary>
        internal static string NoPort {
            get {
                return ResourceManager.GetString("NoPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open serial port.
        /// </summary>
        internal static string NotOpen {
            get {
                return ResourceManager.GetString("NotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not supported.
        /// </summary>
        internal static string NotSupport {
            get {
                return ResourceManager.GetString("NotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave is not online.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened.
        /// </summary>
        internal static string Opened {
            get {
                return ResourceManager.GetString("Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramater error.
        /// </summary>
        internal static string PrmErr {
            get {
                return ResourceManager.GetString("PrmErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave status:.
        /// </summary>
        internal static string SlaveStatus {
            get {
                return ResourceManager.GetString("SlaveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station is not ready for DATA EXCHANGE.
        /// </summary>
        internal static string Station_Not_Ready {
            get {
                return ResourceManager.GetString("Station_Not_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop master first.
        /// </summary>
        internal static string StopMf {
            get {
                return ResourceManager.GetString("StopMf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop monitor first.
        /// </summary>
        internal static string StopTimer5 {
            get {
                return ResourceManager.GetString("StopTimer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync mode.
        /// </summary>
        internal static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        internal static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Ver {
            get {
                return ResourceManager.GetString("Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for PRM.
        /// </summary>
        internal static string WaitPrm {
            get {
                return ResourceManager.GetString("WaitPrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchdog is enabled..
        /// </summary>
        internal static string WatchDog {
            get {
                return ResourceManager.GetString("WatchDog", resourceCulture);
            }
        }
    }
}
