//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQC.Controls {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CQC.Controls.ControlResources", typeof(ControlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Test Case 的本地化字符串。
        /// </summary>
        internal static string TestCaseName {
            get {
                return ResourceManager.GetString("TestCaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!--Conformance Test Cases--&gt;
        ///&lt;TestCase Name = &quot;{0}&quot; Class = &quot;{1}&quot; Type = &quot;&quot; Device = &quot;&quot;&gt;
        ///&lt;Description&gt;
        ///Add test case description here.
        ///&lt;/Description&gt;
        ///
        ///&lt;TestFunctions&gt;
        ///&lt;TestFunction Name = &quot;&quot; ParaNumber = &quot;1&quot; Repeat = &quot;1&quot;&gt;
        ///&lt;Parameters&gt;
        ///&lt;Parameter Name = &quot;&quot; DataType = &quot;visiblestring&quot;&gt;test&lt;/Parameter&gt;
        ///&lt;Parameter Name = &quot;&quot; DataType = &quot;integer&quot;&gt;0000&lt;/Parameter&gt;
        ///&lt;/Parameters&gt;
        ///
        ///&lt;!-- Exepection of Test --&gt;
        ///&lt;Returns Response = &quot;positive&quot;&gt;
        ///&lt;Return Name = &quot;&quot; DataT [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TestCaseTemplate {
            get {
                return ResourceManager.GetString("TestCaseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Class 的本地化字符串。
        /// </summary>
        internal static string TestClassName {
            get {
                return ResourceManager.GetString("TestClassName", resourceCulture);
            }
        }
    }
}
